services:
  - type: web
    name: climatiqq-backend
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: climatiqq-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://climatiqq-frontend.onrender.com,http://localhost:3000,https://rethink-29j0udh6b-yuusuf396s-projects.vercel.app,https://rethink.vercel.app,https://rethink-lake.vercel.app/
      - key: DATABASE_URL
        fromDatabase:
          name: climatiqq-db
          property: connectionString 